export const HISTORICO_DEFAULT_PAGE = 1;

export const HISTORICO_DEFAULT_LIMIT = 20;

export const HISTORICO_MIN_LIMIT = 1;

export const HISTORICO_MAX_LIMIT = 100;

export const HISTORICO_DASHBOARD_DEFAULT_RANKING_LIMIT = 5;

export const HISTORICO_DASHBOARD_MAX_RANKING_LIMIT = 20;

export const HISTORICO_GRAFICO_VACUO_DEFAULT_LIMIT = 1000;

export const HISTORICO_GRAFICO_VACUO_MAX_LIMIT = 5000;
