export enum HardwareCommand {
  INICIAR_BOMBA = 'INICIAR_BOMBA',
  PARAR_BOMBA = 'PARAR_BOMBA',
  ABRIR_VALVULA = 'ABRIR_VALVULA',
  FECHAR_VALVULA = 'FECHAR_VALVULA',
  INICIAR_PROCESSO = 'INICIAR_PROCESSO',
  PAUSAR_PROCESSO = 'PAUSAR_PROCESSO',
  RETOMAR_PROCESSO = 'RETOMAR_PROCESSO',
  FINALIZAR_PROCESSO = 'FINALIZAR_PROCESSO',
  PARADA_EMERGENCIA = 'PARADA_EMERGENCIA',
  SINCRONIZAR_HARDWARE = 'SINCRONIZAR_HARDWARE',
  REINICIAR_COMUNICACAO = 'REINICIAR_COMUNICACAO',
}
