export const MQTT_COMMANDS = {
  LIGAR_BOMBA: 'LIGAR_BOMBA',
  DESLIGAR_BOMBA: 'DESLIGAR_BOMBA',
  DESLIGAR_TODAS_BOMBAS: 'DESLIGAR_TODAS_BOMBAS',
  ABRIR_VALVULA: 'ABRIR_VALVULA',
  FECHAR_VALVULA: 'FECHAR_VALVULA',
  FECHAR_TODAS_VALVULAS: 'FECHAR_TODAS_VALVULAS',
  PARADA_EMERGENCIA: 'PARADA_EMERGENCIA',
  SINCRONIZAR_HARDWARE: 'SINCRONIZAR_HARDWARE',
  REINICIAR_COMUNICACAO: 'REINICIAR_COMUNICACAO',
} as const;

export type CommandName = (typeof MQTT_COMMANDS)[keyof typeof MQTT_COMMANDS];
