export enum EventType {
  // MQTT / CONEXÃO
  MQTT_CONNECTED = 'MQTT_CONNECTED',
  MQTT_DISCONNECTED = 'MQTT_DISCONNECTED',
  MQTT_RECONNECTING = 'MQTT_RECONNECTING',
  MQTT_CONNECTION_FAILED = 'MQTT_CONNECTION_FAILED',

  // MENSAGENS MQTT
  MQTT_MESSAGE_RECEIVED = 'MQTT_MESSAGE_RECEIVED',
  MQTT_MESSAGE_SENT = 'MQTT_MESSAGE_SENT',
  MQTT_MESSAGE_INVALID = 'MQTT_MESSAGE_INVALID',
  MQTT_MESSAGE_PROCESSING_FAILED = 'MQTT_MESSAGE_PROCESSING_FAILED',

  // HEARTBEAT / ESP32
  HEARTBEAT_RECEIVED = 'HEARTBEAT_RECEIVED',
  HEARTBEAT_TIMEOUT = 'HEARTBEAT_TIMEOUT',
  ESP32_ONLINE = 'ESP32_ONLINE',
  ESP32_OFFLINE = 'ESP32_OFFLINE',

  // STATUS DO HARDWARE
  HARDWARE_STATUS_UPDATED = 'HARDWARE_STATUS_UPDATED',
  HARDWARE_STATUS_ALERT = 'HARDWARE_STATUS_ALERT',
  HARDWARE_STATUS_FAILURE = 'HARDWARE_STATUS_FAILURE',

  // LEITURAS / SENSOR DE VÁCUO
  SENSOR_READING_RECEIVED = 'SENSOR_READING_RECEIVED',
  SENSOR_READING_CREATED = 'SENSOR_READING_CREATED',
  SENSOR_READING_OUT_OF_RANGE = 'SENSOR_READING_OUT_OF_RANGE',
  SENSOR_READING_SAFETY_LIMIT_EXCEEDED = 'SENSOR_READING_SAFETY_LIMIT_EXCEEDED',
  SENSOR_READING_TIMEOUT = 'SENSOR_READING_TIMEOUT',
  SENSOR_DISCONNECTED = 'SENSOR_DISCONNECTED',
  SENSOR_FAILURE = 'SENSOR_FAILURE',

  // ACOPLAMENTO DA MANGUEIRA
  ACOPLAMENTO_STATUS_RECEIVED = 'ACOPLAMENTO_STATUS_RECEIVED',
  ACOPLAMENTO_CONNECTED = 'ACOPLAMENTO_CONNECTED',
  ACOPLAMENTO_DISCONNECTED = 'ACOPLAMENTO_DISCONNECTED',
  ACOPLAMENTO_UNKNOWN = 'ACOPLAMENTO_UNKNOWN',
  ACOPLAMENTO_FAILURE = 'ACOPLAMENTO_FAILURE',

  // BOMBAS
  PUMP_STATUS_RECEIVED = 'PUMP_STATUS_RECEIVED',
  PUMP_ACTIVATED = 'PUMP_ACTIVATED',
  PUMP_DEACTIVATED = 'PUMP_DEACTIVATED',
  PUMP_FAILURE = 'PUMP_FAILURE',

  // VÁLVULAS / RELÉS
  VALVE_OPENED = 'VALVE_OPENED',
  VALVE_CLOSED = 'VALVE_CLOSED',
  VALVE_FAILURE = 'VALVE_FAILURE',
  RELAY_FAILURE = 'RELAY_FAILURE',

  // PROCESSO / SEGURANÇA
  PROCESS_START_BLOCKED = 'PROCESS_START_BLOCKED',
  PROCESS_SAFETY_CHECK_FAILED = 'PROCESS_SAFETY_CHECK_FAILED',
  PROCESS_EMERGENCY_STOP_REQUIRED = 'PROCESS_EMERGENCY_STOP_REQUIRED',
  PROCESS_EMERGENCY_STOP_SENT = 'PROCESS_EMERGENCY_STOP_SENT',
  PROCESS_EMERGENCY_STOP_FAILED = 'PROCESS_EMERGENCY_STOP_FAILED',

  // ALARMES
  ALARM_CREATED = 'ALARM_CREATED',
  ALARM_RESOLVED = 'ALARM_RESOLVED',
}
